### ISSUE TITLE
Webseite und Dokumentation automatisch veröffentlichen

### ISSUE THREAD

**Issue by skyfmmf** [ob-algdatii-ss18/leistungsnachweis-mamatofe#10]
Wenn wir in unserem CI-Build die Dokumentation und die Webseite automatisch erzeugen, können wir sie danach auch automatisch veröffentlichen, damit sie immer zum aktuellen Stand passt.

**Comment by skyfmmf** [comment]
Kann also erst nach #8 und #9 passieren.

**Comment by MarEliSeg** [comment]
Vorher müssen #9 und #8 erledigt sein.
