### ISSUE TITLE
validNumbers Implementation

### ISSUE THREAD

**Issue by markuskr97** [ob-algdatii-ss18/leistungsnachweis-mamatofe#13]
As discussed in the meeting, next step is to implement the valid numbers function which returns the valid numbers for each soduko field.

**Comment by MarEliSeg** [comment]
vorher muss #5 gemacht werden

**Comment by skyfmmf** [comment]
wenn #20 vorher erledigt ist, ist das wahrscheinlich auch sehr hilfreich

**Comment by markuskr97** [comment]
Da wir auf #20 verzichten, habe ich jetzt da weitergemacht ...

**Comment by markuskr97** [comment]
Test fehlen noch, werden aber bald gemacht
