### ISSUE TITLE
Implementierung solveNakedSingles()

### ISSUE THREAD

**Issue by MarEliSeg** [ob-algdatii-ss18/leistungsnachweis-mamatofe#14]
- Über das ganze field iterieren, jede einzelne Zelle
- Funktion holt sich mit validNumbers() die möglichen Zahlen für die ausgewählte Zelle
- falls nur ein Wert drin steht -> eintragen
- Rückgabewert boolean, wenn was geändert -> true

**Comment by MarEliSeg** [comment]
vorher muss #13 gemacht sein

**Comment by skyfmmf** [comment]
validNumbers (#13) ist implementiert, daher nicht mehr blocked
