### ISSUE TITLE
Implementierung solveHiddenSingles()

### ISSUE THREAD

**Issue by MarEliSeg** [ob-algdatii-ss18/leistungsnachweis-mamatofe#15]
- über alle Gruppen (Blöcke, Spalten, Zeilen) iterieren
- für jede Gruppe eine Map(1 bis 9) die durch Iteration durch die Gruppe angepasst wird
  - Zahl der Zelle geben lassen: 
    - bei 1-9 Map mit X markieren
    - bei 0, validNumbers() für das Zellegeben lassen
      - Position an jede Stelle in der Map eintragen
      - falls schon eine Position drin steht:
        - mit X markieren
      - falls noch nichts drin steht 
        - Position eintragen
      - falls ein X drin steht
       - nichts machen
- Überprüfung, wo in der Map eine Position steht
  - Wert in Position eintragen

**Comment by MarEliSeg** [comment]
vorher muss #13 gemacht sein

**Comment by skyfmmf** [comment]
validNumbers (#13) ist implementiert, daher nicht mehr blocked
