### ISSUE TITLE
Implementierung Feld-Iteratoren

### ISSUE THREAD

**Issue by markuskr97** [ob-algdatii-ss18/leistungsnachweis-mamatofe#20]

**Comment by markuskr97** [comment]
Braucht man nicht die Iteratoren schon für die Implementierung? Also suche Zeile, Suche Spalte, Suche Block, gebe zurück was geht?

**Comment by markuskr97** [comment]
https://de.wikibooks.org/wiki/C%2B%2B-Programmierung/_Die_STL/_Iteratoren

**Comment by ThoGro** [comment]
Da die Implementierung der Iteratoren für unseren Anwendungsfall zu aufwendig ist, wird darauf verzichtet.
