### ISSUE TITLE
Benchmarking 

### ISSUE THREAD

**Issue by MarEliSeg** [ob-algdatii-ss18/leistungsnachweis-mamatofe#35]
Methode zum Analysieren der Lösung des Sudokus.

- wie viele Zellen waren vor Lösung belegt?
- wie viele wurden von dem jeweiligen Algorithmus gelöst?
- Dauer

in class Sudoku
- von solve() wird die Dauer gespeichert
- jeder einzelne Algorithmus schreibt die Anzahl der gelösten Felder

**Comment by skyfmmf** [comment]
Ich füge dabei auch alle Teile in unserer main zusammen.
