### ISSUE TITLE
Dateiformat für Sudokus

### ISSUE THREAD

**Issue by MarEliSeg** [ob-algdatii-ss18/leistungsnachweis-mamatofe#37]
Sudokus sollen aus csv-Dateien geladen werden.
Repo der Dateien von Herr Braun erfragen.
Implementierung der Einlesung der Sudokus.

**Comment by markuskr97** [comment]
Kurze Frage: Weiß jemand, wie man den Pfad zu Dateien, die in einem bestimmten Ordner liegen, z.B. Testdaten, relativ angeben kann?

**Comment by skyfmmf** [comment]
Normalerweise sollte sowohl `./relativer/pfad/datei.csv` als auch `relativer/pfad/datei.csv` funktionieren
