### ISSUE TITLE
Test-Framework integrieren

### ISSUE THREAD

**Issue by skyfmmf** [ob-algdatii-ss18/leistungsnachweis-mamatofe#5]
Wir brauchen ein Framework für unsere automatischen Tests. Es sollte auch in cmake/ctest integriert werden. Mögliche Tools wären:

- googletest
- catch
- cppunit
- (Boost.Test)
- etc...

**Comment by MarEliSeg** [comment]
- googletest ist solide
- catch ist was Neueres
Am besten zwischen den zwei wählen?!

**Comment by markuskr97** [comment]
Okay, ich werde da mal nachlesen

**Comment by markuskr97** [comment]
http://cppunit.sourceforge.net/doc/cvs/cppunit_cookbook.html

Was haltet ihr davon?

**Comment by skyfmmf** [comment]
Was spricht denn gegen googletest oder catch?

**Comment by markuskr97** [comment]
GoogleTest fände ich auch gut

**Comment by skyfmmf** [comment]
Dann würde ich glaube ich googletest nehmen, das ist verbreiteter, da gibt es hoffentlich eine gute Möglichkeit, das in cmake und ctest zu integrieren.
