### ISSUE TITLE
Webseite erstellen

### ISSUE THREAD

**Issue by skyfmmf** [ob-algdatii-ss18/leistungsnachweis-mamatofe#9]
Wir brauchen eine kleine Webseite für das Projekt. Für das Hosting bietet sich GitHub-Pages an ([https://pages.github.com/#project-site](https://pages.github.com/#project-site)). Wenn wir die HTML-Dateien nicht von Hand schreiben wollen (was ich auch nicht empfehlen würde), sollten wir ein Tool zum Erzeugen benutzen (sog. Static Site Generator). 

Ein Beispiel dafür wäre Sphinx, da kann auch gleich das Tool zur Dokumentation des Codes integriert werden.

**Comment by MarEliSeg** [comment]
Sphinx für die Website und Breathe um es mit Doxygen zu verbinden.
